# Generated by scripts/release/render-homebrew-formula.sh in akiojin/unity-cli.
class UnityCli < Formula
  desc "Rust CLI for Unity Editor automation over the Unity TCP protocol"
  homepage "https://github.com/akiojin/unity-cli"
  version "0.18.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/akiojin/unity-cli/releases/download/v0.18.1/unity-cli-osx-arm64"
      sha256 "73283bfff946a4363affc6093fabaf5aaaf878075e3147ee26a445d30888ba5e"
    end
    on_intel do
      url "https://github.com/akiojin/unity-cli/releases/download/v0.18.1/unity-cli-osx-x64"
      sha256 "bbd4884cb0e7de60241a6c38255486e86e506221586aec6a8412187426f74500"

      # Intel macOS loads ONNX Runtime dynamically for reference embeddings.
      depends_on "onnxruntime"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/akiojin/unity-cli/releases/download/v0.18.1/unity-cli-linux-arm64"
      sha256 "adcf93e3e75fdb29a7262c84d0a3b91a83d7aeee93bf26b4e0c220a366b22f22"
    end
    on_intel do
      url "https://github.com/akiojin/unity-cli/releases/download/v0.18.1/unity-cli-linux-x64"
      sha256 "f0b12f5e4815e77a7c71098903ff9e1dd86ca350dd59e06f50fa27fd256b0a8e"
    end
  end

  def install
    bin.install Dir["unity-cli-*"].first => "unity-cli"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/unity-cli --version")
  end
end
